name: Build Docker Image CI
on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@master

    - name: Build the Docker container image
      run: docker build -t docker.pkg.github.com/dileepcheruku/webapi/webapi:latest .

